# Generated by Django 2.0 on 2022-11-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='classic',
            field=models.BooleanField(default=True),
        ),
    ]
