# Generated by Django 2.0 on 2022-11-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_auto_20180605_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='escaños',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
