# Generated by Django 2.0 on 2022-11-20 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_question_classic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='classic',
        ),
        migrations.AddField(
            model_name='question',
            name='multioption',
            field=models.BooleanField(default=False),
        ),
    ]
