# Generated by Django 2.0 on 2022-11-19 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221116_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='escaños',
        ),
        migrations.AddField(
            model_name='voting',
            name='min_percentage_representation',
            field=models.PositiveIntegerField(default=0.05),
        ),
        migrations.AddField(
            model_name='voting',
            name='seats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
