# Generated by Django 2.0 on 2022-11-19 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0006_auto_20221119_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='limitedInteger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limited_integer_field', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='min_percentage_representation',
        ),
    ]
