# Generated by Django 2.0 on 2022-11-19 11:28

import django.core.validators
from django.db import migrations
import voting.models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0007_auto_20221119_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='limitedInteger',
        ),
        migrations.AddField(
            model_name='voting',
            name='min_percentage_representation',
            field=voting.models.RangeIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
