# Generated by Django 2.0.12 on 2022-12-06 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_auto_20221120_1354'),
        ('voting', '0008_auto_20221119_1128'),
    ]

    operations = [
    ]
